### PR TITLE
Change heading fonts

### PR DESCRIPTION
**Pull request by anatoly-particle**
Preview → https://docs.staging.particle.io

### CODE REVIEW

**Comment by jme783** [comment]
Hey @anatoly-particle, this is almost there. Nice work! What I'm unclear on is why headers are treated differently in some parts of the reference section compared to the guide, FAQ, etc. 

I actually really like how the fonts look when the _only_ use of DIN on the page content are the page titles (`h1`s), while the rest are Avenier. Essentially what I'm suggesting is using the styling on the firmware reference pages across the docs. The most important thing is consistency.

Like this, everywhere:
screen shot 2018-03-14 at 7 11 32 am

Something like:

```
h2 {
  font-family: AvenirNext,sans-serif;
  text-transform: none;
  font-size: 24px;
}

h3 {
  font-family: AvenirNext,sans-serif;
  text-transform: none;
  font-size: 18px;
  letter-spacing: 0;
}

**Review by jme783 — CHANGES_REQUESTED** [review]
See above comment

**Comment by anatoly-particle** [comment]
@jme783, thanks again for the feedback
Here is a small fix to make changes you suggested.
`!important` is a hacky way to do it, but with current styles it is the easiest way to enofrce that styling.
One thing to note is that headings on the sidebar change as well. I like it more:

Before | After
--- | ---
before | after

Changes on staging → https://docs.staging.particle.io/faq/particle-devices/led-troubleshooting/photon/

**Review by jme783 — APPROVED** [review]

**Comment by jme783** [comment]
This looks good. I'd say merge. I do think the icons in the sidebar are still too big. Might be worth a separate small fix:

screen shot 2018-03-15 at 6 33 24 am

screen shot 2018-03-15 at 6 33 41 am

**Comment by anatoly-particle** [comment]
@jme783, I've fixed the icons.
Can you please review changes again?

Before | After
--- | ---
before-icon | after-icon
before-list | after-list

Preview on staging → https://docs.staging.particle.io/reference/javascript/#device-management

**Comment by monkbroc** [comment]
Since you have taken into account all Jeff's feedback, there's no need to wait for an additional review. Let's ship this now.

**Pull request merged**
