### PR TITLE
Update cli.md

### PR DESCRIPTION
**Pull request by dclobato**
Making clear how to solve NPM's permission errors on installing CLI

### CODE REVIEW

**Comment by technobly** [comment]
Thanks @dclobato! Would you please change it as follows (please note the typo as well):

"...change npm's default directory to another directory. Changing the default directory is the preferred choice on a multiuser environment. Both optiokns..."

to 

"...change npm's default directory to another directory (preferred choice on a multiuser environment). Both options..."

**Comment by dclobato** [comment]
Done! :)

**Comment by dclobato** [comment]
Did I miss something on the changes?

**Comment by kennethlimcp** [comment]
@dclobato sorry for the long delay. Pulling this in!

**Pull request merged**
