### PR TITLE
Adding Segment cookie consent manager

### PR DESCRIPTION
**Pull request by davidbbe**
@rickkas7 this is my first time working with the docs website. So bare with me as I dont fully understand the metalsmith framework. This is a very similar set of code changes that we used on the marketing site to set up the Segment cookie consent manager there.

This adds the Segment cookie [consent manager](https://github.com/segmentio/consent-manager) to allow the user to approve or deny cookies. Cookie consent is required for EU and California, but we will have it turned on for all locations as requested by Kate.

This is the same UI/UX that we use on the [marketing site](https://www.particle.io/). Here is a quick video overview of how this will look for users on the docs website. Keep an eye on the applications tab in chrome to see which cookies are loaded. The `tracking-preferences` cookie will be set when the user approves or denies cookies. Inside this cookies is the cookie preferences of the user. While testing you can reset your choice by deleting this `tracking-preferences` cookie. 
https://github.com/particle-iot/docs/assets/5375547/c27680de-69ce-40c7-920e-9db657407dad

## Reviewing locally

I couldnt get the Segment consent-manager script to load for me locally when I was working on this. If you try to run this PR locally then it will probably not see the consent-manager banner pop up. Segment does not seem to work in dev mode and I couldnt figure out how to get around this. But if you replace this like of code `{{#if development}}'mEjdTq9ReorxqwjfYGWbvVNgw4Bg2NXF'{{else}}'PiTQtuDPGp3hKGGN3lU9GJvInSsnKBCR'{{/if}}` with this `'PiTQtuDPGp3hKGGN3lU9GJvInSsnKBCR'` then the local development will work with the consent-manager. Do a search and replace to change that in both locations. That change just runs the production Segment script locally. On production it wouldnt need that change. Im not sure how to deploy to a live staging server so we could hopefully test there as well. 

## Scripts that cause cookies

Segment, Google Analytics, and Marketo Munchkin are the 3 hard coded scripts that we need to block until the user consents to cookies. There is also a Google Tag Manager and SnowFlake script but these two are being loaded through Segment. 

**Google Analytics**: I removed the hard coded Google Analytics script from this repo. We will need to plan on deploying this code at the same time we add Google Analytics through Google Tag Manager. Google Tag Manager is loaded through Segment so that keeps its under this consent-manager. I looked into loading Google Analytics through Segment but that would also require much more code changes of all of the `gtag` events that are used in many places all over the docs repo. Loading Google Analytics through GTM allows the `gtag` events to stay in place. 

**Marketo Munchkin**: The Marketo Munchkin script is a user tracking script. This is already being double loaded on the site though Google Tag Manager and with and script hard coded on the site. I removed the hard coded script and now only the version loaded through Google Tag Manger will be used. 

**Segment**: I updated the Segment script version to the latest in order to use the [consent-manager](https://github.com/segmentio/consent-manager). This script will now only load based on the consent-manager settings that the user chooses. 

**Google Tag Manager**: This is configured through Segment so this will only load based on the consent-manager settings by the user. We are currently using a Google Tag Manager container(ID GTM-P2CPMH) that is shared by multiple Particle websites like build, console, login, and docs. I created a new Google Tag Manager container to serve only the docs website. This removes alot of bloat and unnecessary GTM scripts. But it also allows us to copy over the required scripts for the docs website and install Google Analytics through Google Tag Manager. The new Google Tag Manager container is ID GTM-W7MWHMSN. This container is not yet connected, but this will need to be done as we deploy this PR. Below you can see the shared GTM container and the new docs container. The new container contains a copy of ally the data from the old shared container, minus a few of the tags and scripts that are only triggered on other websites.
Screenshot 2023-09-22 at 12 15 42 AM

## Launch plan

There is one extra step that must be done when we are ready to deploy these changes. We need to switch the Google Tag Manager container to a new copy so that we can include the Google Analytics account in the new Google Tag Manager container. This is a quick and easy change as we just need to change the GTM ID from GTM-P2CPMH to GTM-W7MWHMSN in the Segment settings. That can be done as we deploy the code. Doing this early in the morning or late at night can minimize any Analytics tracking down time. The old container is shared with the build, console, and login websites so we new to use a different container that allows us to add Google Analytics into GTM without that being used on other domains. 
When this PR is approved, lets pick a time like early morning to deploy, make the necessary changes in Google Tag Manager, and test the new GTM container and GA data.

### CODE REVIEW

**Review by rickkas7 — APPROVED** [review]
Looks good! I ran the local test and was prompted. I think you have permission to Squash and Merge this PR and then you can coordinate the change in GTM more easily. If that doesn't work we can pick a time and I can merge. It takes about 9 minutes for CI to complete and it deploy to production. You can monitor the status here: https://app.circleci.com/pipelines/github/particle-iot/docs . There is no working staging environment right now.

**Comment by davidbbe** [comment]
@rickkas7 can we deploy this PR today? Does the PR merge request auto deploy the code to production? If it does then I can do that and update the Segment GTM container ID to the new version.

**Comment by rickkas7** [comment]
Yes. I can Squash and merge it right now, then it will be live in ~9 minutes, or at a time of your choosing today, then you can update the Segment GTM container ID.

**Comment by davidbbe** [comment]
@rickkas7 ok great. Ill keep an eye on this PR and CircleCI. Ill make sure to update the GTM container as its deploying.

**Pull request merged**
