### PR TITLE
Feature/faq eclipse debug

### PR DESCRIPTION
**Pull request by rickkas7**
FAQ for debugging using JTAG/SWD, Eclipse and OpenOCD

### CODE REVIEW

**Comment by monkbroc** [comment]
Do you need a review since I wrote some OpenOCD guides too?

**Comment by rickkas7** [comment]
Usually Will reviews the FAQs, but if you'd like to provide additional input that would be welcome as well.

**Comment by brandoaire** [comment]
@monkbroc I think you or @technobly would be best to review this one since it's a pretty technical one!

**Comment by technobly** [comment]
I think it would be useful for someone to actually go through it and follow it to see what snags come up.  I don't have the time this week though, but next week I could look at it!

**Comment by monkbroc** [comment]
This guide is massive!

I reordered the top a bit. I put a link to the store for the Programmer Shield.

I'm not able to install the Eclipse plugins due to some Java SSL issues :( I think the cypher used by Sourceforge is not compatible with the latest JDK I have.

**Comment by rickkas7** [comment]
It is indeed massive. It took a while to write, but it took forever to verify and take the screen shots because I did it on clean VM images of OS X, Windows 10 and Linux, and parts of it on Windows 7 as well. It was insane!

**Comment by brandoaire** [comment]
Are we ready to merge? @monkbroc or @technobly  feel free to pull the trigger if you've read through it.

**Comment by monkbroc** [comment]
I'm getting the same certificate exception when trying to install the GNU ARM Eclipse extension on Eclipse for Windows. I will try to update the Java version on my Windows machine.

image


I want to make sure to address this since I had the same error on 2 machines with a different OS.

**Comment by rickkas7** [comment]
I'll re-run a test this weekend, if a resolution isn't found before then.

**Comment by monkbroc** [comment]
I opened a GitHub issue with the GNU ARM Eclipse plugin. I tried Window and Linux with the latest JDK but I still couldn't get the plugin to install.
https://github.com/gnuarmeclipse/plug-ins/issues/171

**Comment by rickkas7** [comment]
I see what you mean now. That definitely used to work, because I did it at least 5 times, but it fails for me now as well.

```
Unable to read repository at http://gnuarmeclipse.sourceforge.net/updates/content.xml.
Unable to read repository at http://gnuarmeclipse.sourceforge.net/updates/content.xml.
Received fatal alert: handshake_failure
```

I guess we'll have to wait until that's fixed.

**Comment by monkbroc** [comment]
I would guess Sourceforge changed their SSL cert provider and Java doesn't trust the CA they used.

**Comment by monkbroc** [comment]
I updated the steps to do a manual install of the plugin. It's not even more complicated.

I followed the steps until the end so we're good to go! :100: thanks for writing all of this, with screenshots! I know I'm going to use it :grinning:

**Pull request merged**
