### PR TITLE
system threading docs.

### PR DESCRIPTION
**Pull request by m-mcgowan**
Current WiP for the new system threading mode on Photon/Electron.

### CODE REVIEW

**Comment by jme783** [comment]
@m-mcgowan what is the status of this P/R? Is it still relevant? If so, can you resolve the merge conflicts and I'll merge in?

**Comment by m-mcgowan** [comment]
It's relevant, but only for a future release. (I like to write the docs early in feature development, and this feature isn't released yet.) Would be ideal if `firmware.md` was in the firmware repo so we can manage docs for each feature and release them with firmware releases.

**Comment by technobly** [comment]
@m-mcgowan Just double checking if this is still relevant or if you have created a new version of it.  I see something a bit different released with v0.4.6 firmware: https://docs.particle.io/reference/firmware/photon/#system-thread

**Comment by m-mcgowan** [comment]
We can throw this out. I redid the threading section. I'll close!

**Pull request closed without merging**
