### PR TITLE
Fix Wi-Fi mention for Electron `Particle.process()`

### PR DESCRIPTION
**Pull request by bsatrom**
Quick fix to the Electron docs for Particle.process

### CODE REVIEW

**Review by anatoly-particle — APPROVED** [review]
👍

**Comment by monkbroc** [comment]
To avoid duplication when the only difference is the type of network, use the `{{network-type}}` helper.

See definition in https://github.com/particle-iot/docs/blob/41aaaa1839e27dae6f0bf54427f2a30dd2be0e3f/templates/helpers/network-type.js and usage in https://github.com/particle-iot/docs/blob/7cfbd748324c71b8374690788cf5a6691cdf9054/src/content/support/troubleshooting/troubleshooting-support.md

@bsatrom Do you want to open another PR with `{{network-type}}` replacing Wi-Fi in the original commit?

Other helpful helpers are `{{device}}`, `{{a-device}}`, `{{reset-button}}`, `{{system-button}}` and the `{{if has-<feature>}}` construct where `<feature>` can be any of the strings in https://github.com/particle-iot/docs/blob/41aaaa1839e27dae6f0bf54427f2a30dd2be0e3f/config/device_features.json

**Comment by anatoly-particle** [comment]
Very useful! Thanks, @monkbroc!

Side note: `network-type` helper will return lowercased **_“cellular”_**.

**Comment by bsatrom** [comment]
Thanks @monkbroc, will do!

**Comment by monkbroc** [comment]
> Side note: network-type helper will return lowercased “cellular”.

If that's a problem you can always define a new helper called `titltecase` similar to https://github.com/particle-iot/docs/blob/41aaaa1839e27dae6f0bf54427f2a30dd2be0e3f/templates/helpers/titleize.js and use it like `{{titlecase network-type}}`

**Comment by bsatrom** [comment]
To @anatoly-particle's point, what can we do in the case where the docs are referring to the WiFi or Cellular classes? Is there a helper for these as well?

**Comment by monkbroc** [comment]
Make a new helper :)

**Comment by bsatrom** [comment]
that's what I was just wondering. :D Will do.

**Comment by monkbroc** [comment]
Actually do you have specific instances of referring to WiFi or Cellular class? That sounds rare enough that it might be easier to just do `{{if has-wifi}}` or `{{if has-cellular}}`

**Comment by bsatrom** [comment]
`Particle.process()` was one place I came across it: https://docs.particle.io/reference/firmware/electron/#particle-process-

> Even in non-cloud-bound applications it can still be advisable to call Particle.process() to explicitly provide some processor time to the Cellular module (e.g. immediately after Cellular.ready() to update system variables).

**Comment by monkbroc** [comment]
If it's just one case, then I'd do this:

```
Even in non-cloud-bound applications it can still be advisable to call Particle.process() to explicitly provide some processor time to the {{network-type}} module (e.g. immediately after {{if has-wifi}}WiFi{{else}}{{if has-cellular}}Cellular{{/if}}{{/if}}.ready() to update system variables).
```

It's not generalized, but it's also hard to know if it will apply for future boards that won't have Wi-Fi or cellular.

**Comment by bsatrom** [comment]
Thanks Julien, will do

**Pull request merged**
