### PR TITLE
Feature/eeprom update

### PR DESCRIPTION
**Pull request by satishgn**
For firmware PR: https://github.com/spark/firmware/pull/428

### CODE REVIEW

**Comment by technobly** [comment]
FYI this also has updates to docs for SPI DMA: https://github.com/spark/firmware/pull/430

**Comment by jme783** [comment]
@satishgn assuming this is now out of date or has been added to the new firmware page with the new docs structure. If not, please re-open the P/R after pulling `master` and adding to the new repo structure.

**Comment by technobly** [comment]
These docs are needed, the feature was recreated and pull in on a different PR.

**Comment by m-mcgowan** [comment]
rebased and merged into #156

**Pull request closed without merging**
