### PR TITLE
Add a few missing double quotes to JSON strings

### PR DESCRIPTION
**Pull request by monkbroc**
The docs should be consistent and show valid JSON everywhere ;-)

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@dmiddlecamp or @emilyrose  can you guys confirm this? :)

**Comment by dmiddlecamp** [comment]
technically yes!  Proper JSON strings have their properties quoted with double quotes :)   Thanks!

**Comment by kennethlimcp** [comment]
Thanks @monkbroc  :)

**Comment by monkbroc** [comment]
I had to add the quotes after I pasted the template in my code, so I
figured it would be useful to update the docs so others don't have to.

Keep up the good work 👍

**Pull request merged**
