### PR TITLE
docs for system interrupt handlers

### PR DESCRIPTION
**Pull request by m-mcgowan**
creating a PR for peer review.

### CODE REVIEW

**Comment by andyw-lala** [comment]
I think you should explicitly state whether or not the tone/pwm timers are started and active regardless of whether any tone or pwm functions are used, as well as the frequency at which the interrupts occur.

Also specify the relationship between other events resulting from the interrupt (e.g. do these hooks get called before/after other code.)

**Comment by jme783** [comment]
@m-mcgowan assuming that this was added to our new firmware page in the new docs. If not, feel free to re-open the P/R. Closing for now

**Comment by technobly** [comment]
Yep, we need this in the docs :)

**Comment by technobly** [comment]
@m-mcgowan I was looking to convert this over to the new Docs (currently this is written for the old Docs)... and I wanted to just get the info out there so people can start consuming it.  However, after reading it I'm not exactly sure how these system interrupts are initialized or configured.  The handlers make sense, but what "fires" these?  A concrete example with a timer with values would go a long way.  Thanks!

**Comment by pkourany** [comment]
Folks, there is a much longer list of timer interrupts than the ones you list.  Each timer also has 4 channels, each with interrupts for example.  I believe a more involved explanation may be warranted.

**Comment by technobly** [comment]
You know it @pkourany!  Hey are you using this for your TimerInterval library?  Any chance you want to add some details?  I know writing docs can be a bore, but when you are really into a feature the details can flow pretty easily.  Any help would be appreciated, even if you just paste in a simple example.

**Comment by ensonic** [comment]
I am a bit late here, but can't figure how to make regullar irq handlers like:
'''
void DMA1_Stream5_IRQHandler(void)
'''

If you only support a subset (like timers), can you please explicitely say that?

**Comment by chobberoni** [comment]
@m-mcgowan what's the status on this PR? merge of too old of a format to merge?

**Comment by m-mcgowan** [comment]
I'll submit a new PR after copying the changes into the current docs.

**Pull request closed without merging**
