### PR TITLE
Flesh out the CAN documentation

### PR DESCRIPTION
**Pull request by monkbroc**
Documentation for spark/firmware#790

### CODE REVIEW

**Comment by bspranger** [comment]
I think this looks like a great start for the documentation.   The link to the wiki is a great idea so we don't have to detail all the specifics about CAN.

**Comment by monkbroc** [comment]
If there's anything you want to add or modify, you can push changes to my branch and the pull request will be updated.

You could also write your changes as comments here.

**Comment by technobly** [comment]
Oooh, nice!  I didn't know there was this much activity on the CAN docs.  Thanks!!

**Comment by monkbroc** [comment]
@technobly This hasn't been merged yet but the CAN driver is released now in firmware 0.4.9. Is there anything blocking merging this in?

**Comment by technobly** [comment]
@monkbroc I wasn't sure if you were still adding to this PR or not.  If you think it's ready to go we will definitely merge :)  Just say the word.

**Comment by monkbroc** [comment]
:shipit:

**Comment by technobly** [comment]
Hmm, there does appear to be some merge conflicts as I recently updated the CAN docs for electron release.  I think there are a few minor things I changed which would be worth incorporating here.  If you want to rebase this against `master` and resolve the conflicts that would be helpful.  Otherwise I can do this later on today.  Sorry! :grin:

**Comment by monkbroc** [comment]
I'll let you do it since I originally opened the PR against the 0.4.9 branch. GitHub won't let me change the target branch to `master`. Just cherry-pick this commit on top of `master` then close this PR.

**Pull request closed without merging**
