### PR TITLE
feature/cli-updated-dev-info

### PR DESCRIPTION
**Pull request by busticated**

### CODE REVIEW

**Review by rickkas7 — APPROVED** [review]

**Comment by rickkas7** [comment]
However, your build will likely fail because of a changed link in the store. I'll fix that tomorrow if no one has fixed it first.

**Comment by busticated** [comment]
@rickkas7 ah, ok. no sweat :+1:

i see:

```
The command "./scripts/update-api.sh" failed and exited with 128 during .
```

over in travis - i assume that's the error you are referring to?

**Comment by rickkas7** [comment]
So that's Julien's fix for the changed tag on the api-service. However, that hasn't been released because of a changed store link, which prevent that travis build from succeeding.

**Comment by busticated** [comment]
@rickkas7 got it. i'm ok to merge though, correct?

**Comment by rickkas7** [comment]
Yes, though it won't go live until the previous problems are fixed. I'm about to commit the store fix, which should unblock all of the other changes.

**Pull request merged**
