### PR TITLE
Organizations tutorial

### PR DESCRIPTION
**Pull request by jme783**
Create a tutorial for Organizations, a new Enterprise feature.

### CODE REVIEW

**Review by rickkas7 — APPROVED** [review]
Looks great!

**Comment by idokleinman** [comment]
I'm taking over this branch to coordinate it's editing+release with the Orgs release

**Comment by idokleinman** [comment]
Waiting on approval until we fill in the TODOs + verify screenshots

**Review by idokleinman — APPROVED** [review]
I approved, improved and merged it via a rebase

**Pull request closed without merging**
