### PR TITLE
[community] Add a page about po-util to "Tools and Features"

### PR DESCRIPTION
**Pull request by nrobinson2000**
I was thinking that we could add a page about po-util, the script that I have been developing into the Particle documentation.  I have been using it for all of my Particle development and I think that other users will benefit from having it in the documentation.

### CODE REVIEW

**Comment by monkbroc** [comment]
I agree that installing all these tools is hard. One of my current tasks is creating installers for the Particle tools. I'm starting with the CLI and later I'll do one for the local compiler. I'll take a look at your Linux and OSX script, but I don't think I want to include all the functionality into a tool installer. Some of that functionality like local build belongs in the CLI in the long run.

**Comment by nrobinson2000** [comment]
> I don't think I want to include all the functionality into a tool installer.

Why not?  It works smoothly for me.  Its also very easy to install.

> Some of that functionality like local build belongs in the CLI in the long run.

True.  But I think that for now my script is good enough.

**Comment by nrobinson2000** [comment]
Po-util is more of a wrapper than a tool.  It makes it easier to do difficult tasks like installing the necessary build tools and building locally.

**Comment by kennethlimcp** [comment]
Happy to add this under `community.md` as a link but not a page itself

**Comment by nrobinson2000** [comment]
Yes, a link would be perfect.

**Comment by nrobinson2000** [comment]
@kennethlimcp 
Any update on adding a link to po-util in the docs?  Do I have to create a pull request for this?

**Comment by technobly** [comment]
@nrobinson2000 I tagged this issue with the **[community]** tag so that when we have a page figured out for Community projects, libraries, tools we will resolve these related issues at that time.  @cmsunu28 may be working on this page already (or in the future) if I remember correctly.

**Comment by nrobinson2000** [comment]
That sounds great.  I did just make this pull request however.  https://github.com/spark/docs/pull/538

**Comment by monkbroc** [comment]
I merged in #538 so I'll close this one.

**Pull request closed without merging**
