### PR TITLE
Add Windows SDK to reference docs

### PR DESCRIPTION
**Pull request by justmobilize**

### CODE REVIEW

**Comment by monkbroc** [comment]
Justin! Nice work!

I'll proofread the new content. Let me know when the Windows SDK is live so it's appropriate to show this on the live docs website.

**Comment by justmobilize** [comment]
Thanks Julien. Everything is live at this point (SDK, Setup Library and App).  I would check with @idokleinman for when to pull trigger.

**Comment by idokleinman** [comment]
@monkbroc I want to sync it with community announcement / docs/ website landing page / social

**Comment by monkbroc** [comment]
I'll let you pull the trigger when you think it's time @idokleinman. We can always fix any small typos later.

**Comment by idokleinman** [comment]
Thanks @monkbroc - if you see something feel free to pull the the branch and edit. I plan to pull the trigger later today

**Comment by monkbroc** [comment]
I made a few typo changes. I also removed the hint to label issues as <kbd>bug</kbd> since only Particle team members can add labels to issues.

**Pull request merged**
