### PR TITLE
edit: tweak device argument wording for cli compile command

### PR DESCRIPTION
**Pull request by bsatrom**
Tweaked the wording of the device section of the `particle compile` reference doc.

### CODE REVIEW

**Review by monkbroc — APPROVED** [review]
Great!

**Comment by monkbroc** [comment]
You can also try adding
```
---
```
on a separate line to force a line break on both columns.

**Comment by monkbroc** [comment]
Feel free to hit Merge when this is done. It will auto-deploy to docs.particle.io

**Comment by bsatrom** [comment]
@monkbroc Should I do that after the [code snippet](https://github.com/particle-iot/docs/pull/752/files#diff-e76470f081bcfa60d0aa14912abb8ee4R235), the text of both?

**Comment by monkbroc** [comment]
Try it out.

**Pull request merged**
