### PR TITLE
Update docs for Particle.variable() and Particle.function()

### PR DESCRIPTION
**Pull request by sergeuz**
This PR tightens up the wording as to when cloud function and variables need to be registered in the application code, and adds docs for a [new feature](https://github.com/particle-iot/device-os/pull/1998) which will be included in Device OS 1.6.0 and allow registering C++ functions as cloud variables.

### CODE REVIEW

**Review by rickkas7 — APPROVED** [review]
Looks good, thanks!

**Comment by rickkas7** [comment]
I updated the crawler to treat 403 errors from Adafruit as warnings so if you update from master or rebase to pick up the change you should be able to get a clean Travis build so you can merge.

**Comment by sergeuz** [comment]
[ch47300]

**Comment by sergeuz** [comment]
> I updated the crawler to treat 403 errors from Adafruit as warnings so if you update from master or rebase to pick up the change you should be able to get a clean Travis build so you can merge.

Thank you! Travis is green now. I'll rebase this PR once again and merge it when 1.6.0 is released.

**Comment by avtolstoy** [comment]
FYI this accidentally got into 1.5.0-rc.2.

**Comment by sergeuz** [comment]
@rickkas7 Can we close this given that https://github.com/particle-iot/docs/pull/1093 is merged and seems to contain all the changes from this PR?

**Pull request closed without merging**
