### PR TITLE
Update cli.md

### PR DESCRIPTION
**Pull request by dclobato**
Keeping clear that npm {install|uninstall} should be run as root

### CODE REVIEW

**Comment by technobly** [comment]
Thanks @dclobato, this is a persistent issue with many people.  `sudo` is the quick fix, but this is likely just a NPM permissions issue that can be solved thusly: https://docs.npmjs.com/getting-started/fixing-npm-permissions

Easy to recommend `sudo` but let's let @emilyrose comment on this. Emily, do you have a preference for instructions here?

**Comment by dclobato** [comment]
Hi. Reading the docs pointed out, I do not think that change the ownership of NPM's directory is a global solution, specially on a multiuser environment... :)

**Comment by technobly** [comment]
@dclobato in that case use Option 2 so you have your own NPM default directory :) https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npm-s-default-directory-to-another-directory

**Comment by affinity-matrix** [comment]
Option 2 is the method I recommend to folks facing NPM permissions issues with global installs!

**Comment by technobly** [comment]
:+1:

**Comment by affinity-matrix** [comment]
@dclobato while this particular change won't land, I would be more than happy if you wanted to be the one to submit the patch mentioning the NPM documentation on permissions! If not I totally understand :smile_cat:

**Comment by affinity-matrix** [comment]
If so, just re-open this PR with the changes, or open a new one! Thanks!

**Pull request closed without merging**
