### PR TITLE
Make table of contents Javascript fast

### PR DESCRIPTION
**Pull request by monkbroc**
The Javascript code to synchronize the table of contents with the scroll position was slow, taking over 30s to run on page load for the firmware reference page. #225

This PR removes the jQuery Inview plugin and replaces it with a `scroll` event listener to update the table of contents. Loading the firmware reference page now takes less than 3 seconds. :rocket:

It also moves showing/hiding the menu to CSS and doesn't twiddle the guide next arrow to speed up page load (both of these things needed the layout to finish before the Javascript continued).

### CODE REVIEW

**Comment by jme783** [comment]
@monkbroc this is freakin' fantastic! Thank you for doing this. Can you point me in the right direction to let me run this locally? I just want to run some smoke tests before merging

**Comment by monkbroc** [comment]
You can follow the instructions in the readme: `npm install`, `npm start` and browse to `http://localhost:8080`

**Comment by jme783** [comment]
Sorry, I meant a link to your fork of the repo / your branch so I can clone it

**Comment by monkbroc** [comment]
> link to your fork of the repo / your branch

Quite inconvenient that GitHub doesn't provide a link to the fork...

```
# in your docs folder
git remote add monkbroc https://github.com/monkbroc/particle-docs.git
git fetch monkbroc
git checkout -b monkbroc/feature/fast-toc
```

**Comment by jme783** [comment]
Fantastic, thanks!

**Comment by jme783** [comment]
Looks amazing. Merging

**Comment by brycekahle** [comment]
@monkbroc :+1:

**Comment by moors7** [comment]
image

This has been annoying for so long that this is a really welcome change, thanks a lot!
(while we're on the menu thing anyways, is there a way to show the drop-down menu on the pages you haven't got open? Currently you first have to go to the 'parent' page before you see the '+' with its children. Would be neat to have that available always.)

**Comment by monkbroc** [comment]
Thanks @jme783, @brycekahle and @moors7 

I've been looking at your [feature list](http://community.particle.io/t/backlog-feature-request/18578) @moors7. You can take C3 out now :)

I didn't understand the "Better navigation (allow me to go into submenus from anywhere)" but now that you explained it, it makes sense.

**Pull request merged**
