### PR TITLE
Add link to OLED example code

### PR DESCRIPTION
**Pull request by briangershon**
It took awhile to figure out which software and which wiring I needed for my OLED that came with the Photon. This link will help others get started.

See also the PR I just submitted to help user figure out which OLED (hardware or software SPI) they have: https://github.com/pkourany/Adafruit_SSD1306/pull/10

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@pkourany @ScruffR looks good?

**Comment by ScruffR** [comment]
Maybe another link to the [Build library](https://build.particle.io/libs/5397d8d028979ed3cc000731) would be good too

**Comment by briangershon** [comment]
Hi @kennethlimcp and @ScruffR 

I added a link to the Build Library.

**Comment by briangershon** [comment]
Thanks @ScruffR -- @kennethlimcp this looks good to go, thanks!

**Comment by kennethlimcp** [comment]
Done :)

**Pull request merged**
