### PR TITLE
number of var/func is out dated #304

### PR DESCRIPTION
**Pull request by hkmoca**
fixed issue #304 changed description of the current supported var/func on Particle.

### CODE REVIEW

**Comment by monkbroc** [comment]
Thanks. I was updating this section of the docs today. I'll include your change.

**Comment by monkbroc** [comment]
Before writing in the docs that there is no limit, I'd like to test what happens when you register more variables than actually fits in the description message.

**Comment by hkmoca** [comment]
hi man! how are you doing? 
Is there anything that i could help you to merge this one?

**Comment by monkbroc** [comment]
Since the number of functions and variables is limited by the size of the discovery message I'd rather not say "unlimited" in the docs, otherwise somebody might create a Particle.variable for every variable in their software. I need to check the practical limit.

**Comment by monkbroc** [comment]
I've verified that up to 20 variables and 15 functions fit in the "describe" message sent by the device to the cloud. I'm updating the docs to reflect that in #397.

**Pull request closed without merging**
