### PR TITLE
Use SVG animations for RGB LED demonstrations

### PR DESCRIPTION
**Pull request by monkbroc**
Here's an easier way to add RGB LED demonstrations to the docs. This will come in handy when the docs are updated for the Electron.

As a first step I converted the animations in the getting started section, but I think that page should only contain the 3-4 most common patterns with the advanced ones like DFU and SOS moved to a reference page.
## Demo

device-anim2
## Features
- Includes the Core and Photon image by @technobly (Electron soon to follow? :wink:)
- Supports breathing, blinking, SOS and arbitrary patterns
- Add device animations in any docs page
- Device image and patterns are easy to customize
## Usage

Add a line like this to the markdown docs `{{{device-animation device "breathe" "cyan" }}}`
## Changes
- Add Handlebar helper `device-animation`
- Add browser JS to implement device animation
- Add SVG.js to create SVG canvas and animate LED
- Add `device` variable to Handlebar template so that `{{device}}` inserts Photon/Core
- Correct weird spelling in titleize helper
## Browser compatibility
- Chrome
- Firefox
- IE11
- Android
- I don't currently have access to old IE or Apple browsers

### CODE REVIEW

**Comment by andyw-lala** [comment]
Excellent stuff.

Minor comment - with sequence animations like the "typical pattern of a
Photon after power up", a delimiter showing when the sequence starts and
stops, a progress bar or something similar would be good. After a while,
you scroll up to the animation and it's just looping with no obvious
beginning or end (unless you already knew the pattern.)

On Wed, Dec 30, 2015 at 2:33 PM, Julien Vanier notifications@github.com
wrote:

> Here's an easier way to add RGB LED demonstrations to the docs. This will
> come in handy when the docs are updated for the Electron.
> 
> As a first step I converted the animations in the getting started section,
> but I think that page should only contain the 3-4 most common patterns with
> the advanced ones like DFU and SOS moved to a reference page.
> 
> [image: device-anim2]
> https://cloud.githubusercontent.com/assets/1919681/12056934/2ec27bde-af0a-11e5-98df-0601a4bd59f0.gif
> Features
> - Supports breathing, blinking, SOS and arbitrary patterns
> - Add device animations in any docs page
> - Device image and patterns are easy to customize
> 
> Usage
> 
> Add to the docs markdown {{{device-animation device "breathe" "cyan" }}}
> Changes
> - Add helper for device-animation
> - Add JS to implement device animation
> - Add SVG.js to create SVG canvas and animate LED
> - Add device variable to template so that {{device}} inserts
>   Photon/Core
> - Correct weird spelling in titleize helper
> 
> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/spark/docs/pull/255
> Commit Summary
> - Use SVG animations for RGB LED demonstrations
> 
> File Changes
> - _D_ api-node https://github.com/spark/docs/pull/255/files#diff-0
>   (1)
> - _M_ scripts/fork.js
>   https://github.com/spark/docs/pull/255/files#diff-1 (3)
> - _A_ src/assets/images/core.svg
>   https://github.com/spark/docs/pull/255/files#diff-2 (326)
> - _M_ src/assets/images/photon.png
>   https://github.com/spark/docs/pull/255/files#diff-3 (0)
> - _A_ src/assets/images/photon.psd
>   https://github.com/spark/docs/pull/255/files#diff-4 (0)
> - _A_ src/assets/images/photon.svg
>   https://github.com/spark/docs/pull/255/files#diff-5 (616)
> - _D_ src/assets/js/animated-core.js
>   https://github.com/spark/docs/pull/255/files#diff-6 (37)
> - _A_ src/assets/js/device-animation.js
>   https://github.com/spark/docs/pull/255/files#diff-7 (266)
> - _A_ src/assets/js/svg.min.js
>   https://github.com/spark/docs/pull/255/files#diff-8 (2)
> - _M_ src/assets/less/getting-started.less
>   https://github.com/spark/docs/pull/255/files#diff-9 (5)
> - _M_ src/content/guide/getting-started/modes.md
>   https://github.com/spark/docs/pull/255/files#diff-10 (255)
> - _M_ templates/guide.hbs
>   https://github.com/spark/docs/pull/255/files#diff-11 (2)
> - _A_ templates/helpers/device-animation.js
>   https://github.com/spark/docs/pull/255/files#diff-12 (8)
> - _R_ templates/helpers/titleize.js
>   https://github.com/spark/docs/pull/255/files#diff-13 (0)
> - _M_ templates/partials/scripts.hbs
>   https://github.com/spark/docs/pull/255/files#diff-14 (3)
> - _M_ templates/support.hbs
>   https://github.com/spark/docs/pull/255/files#diff-15 (2)
> 
> Patch Links:
> - https://github.com/spark/docs/pull/255.patch
> - https://github.com/spark/docs/pull/255.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spark/docs/pull/255.

## 

Andy

**Comment by monkbroc** [comment]
Good idea to add an optional progress bar below the animation Andy.

**Comment by andyw-lala** [comment]
And did I mention these rock ?

On Wed, Dec 30, 2015 at 2:59 PM, Julien Vanier notifications@github.com
wrote:

> Good idea to add an optional progress bar below the animation Andy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spark/docs/pull/255#issuecomment-168072885.

## 

Andy

**Comment by chobberoni** [comment]
these are stellar!

**Comment by monkbroc** [comment]
Another side effect of this PR: You can now use `{{device}}` in a docs markdown template to insert Photon, Core or Electron (when those pages are added).

So no more `{{#if photon}}Photon{{else}}Core{{/if}}` which will break when the Electron is added...

**Comment by mohitbhoite** [comment]
BEAUTIFUL!!

**Comment by chobberoni** [comment]
hey @monkbroc can you make/change this PR to the staging branch? i want to test some stuff out without breaking out master branch. thanks!

**Comment by monkbroc** [comment]
Thanks @chobberoni!

**Comment by technobly** [comment]
Excellent work @monkbroc !

**Comment by monkbroc** [comment]
Thanks Brett 👌

**Pull request merged**
