### PR TITLE
Describe what the mysterious signal does.

### PR DESCRIPTION
**Pull request by monkbroc**
Was that meant to be a secret @dmiddlecamp?

Nyan cat

### CODE REVIEW

**Comment by dmiddlecamp** [comment]
Yea that's an Easter egg, not meant to be documented ;)

**Comment by monkbroc** [comment]
You leave just enough evidence by mentioning it in the Javascript SDK docs but not enough to explain what it does. I respect that.

**Comment by moors7** [comment]
I do think this could be useful in the (web) IDE, as an "identify" button. On more than one occasion I have flashed the wrong device because I didn't know which was which. Having the ability to make it shout rainbows would be useful. Just a thought.

**Comment by dmiddlecamp** [comment]
Ah, I spoke too early, the command in the CLI is an easter egg, but the api / SDKs should definitely be documented.  :)  

Here's the secret CLI command:

particle nyan 
particle nyan [on/off]
particle nyan device_id [on/off]

:)

**Comment by moors7** [comment]
Should we then hide this as to not spoil it?
https://community.particle.io/t/what-does-sparkapi-prototype-signalcore-do/12741/4

**Comment by dmiddlecamp** [comment]
I'm happy if people discover it, no need to hide it any more than it is already.  :)

**Comment by monkbroc** [comment]
So are you OK adding the note I put here to the Javascript SDK docs, and also adding a section in the Cloud API docs that explains you can include "signal" in the device PUT call, but leaving the nyan command out of the CLI docs?

The initial text of the PR was confusing. @dmiddlecamp assumed I proposed to document the nyan CLI command where I wanted to clarify an already existing section of the Javascript SDK docs that really puzzled me.

Actually @moors7 I found out about the nyan command because I was about to implement a `particle rainbow` command in a fork of the CLI for exactly the purpose you describe: to quickly identify a particular device from a pile. I also think it would be useful to have a "Who am I?" button in the devices view of the web IDE.

**Comment by dmiddlecamp** [comment]
:+1:

**Comment by jme783** [comment]
@monkbroc  assuming this is now out of date or has been added to the new docs. If not, please re-open the P/R after pulling `master` and adding to the new repo structure.

**Pull request closed without merging**
